cleanups

diff --git a/wpsd-update b/wpsd-update
--- a/wpsd-update
+++ b/wpsd-update
@@ -368,25 +368,27 @@ perform_update() {
     echo -e "  ${TICK} Done!\n"
 
 
+    if [ -t 1 ]; then
     # This is running from a terminal, so it should be safe to update the OS
-    if [ "$1" == "os" ]; then
-	echo -e "${BULL} Checking for any available operating system updates."
-	echo -e "  Please wait..."
-	apt-get -q=2 update
-	if ! apt-get upgrade --dry-run | grep -qw "0 upgraded"; then
-	    echo -e "  ${COL_LIGHT_MAGENTA}${INFO} Operating system updates available; installing now..."
-	    apt-get upgrade --fix-missing --fix-broken -y
-	    apt-get -q=2 autoremove -y
-	    apt-get -q=2 clean
-	    apt-get -q=2 autoclean
-	    echo -e "  ${TICK} Done!\n"
+	if [ "$1" == "os" ]; then
+	    echo -e "${BULL} Checking for any available operating system updates."
+	    echo -e "  Please wait..."
+	    apt-get -q=2 update
+	    if ! apt-get upgrade --dry-run | grep -qw "0 upgraded"; then
+		echo -e "  ${COL_LIGHT_MAGENTA}${INFO} Operating system updates available; installing now..."
+		apt-get upgrade --fix-missing --fix-broken -y
+		apt-get -q=2 autoremove -y
+		apt-get -q=2 clean
+		apt-get -q=2 autoclean
+		echo -e "  ${TICK} Done!\n"
+	    else
+		echo -e "  ${INFO} No operating system updates required.\n"
+	    fi
 	else
-	    echo -e "  ${INFO} No operating system updates required.\n"
+	    echo -e "${BULL} ${COL_LIGHT_BLUE}${INFO} Operating system is ${BOLD}not${COL_NC} updated by default..."
+	    echo -e "      To check for and install OS updates, run this"
+	    echo -e "      program again as: '${COL_LIGHT_BLUE}${BOLD}sudo wpsd-update os${COL_NC}'\n"
 	fi
-    else
-	echo -e "${BULL} ${COL_LIGHT_BLUE}${INFO} Operating system is ${BOLD}not${COL_NC} updated by default..."
-	echo -e "      To check for and install OS updates, run this"
-	echo -e "      program again as: '${COL_LIGHT_BLUE}${BOLD}sudo wpsd-update os${COL_NC}'\n"
     fi
 
     /bin/sync
@@ -411,7 +413,7 @@ if [ -t 1 ]; then
     # run via terminal, only output to screen
     export FORCE_COLOR=1
     term_banner
-    perform_update "$0" "$@"
+    perform_update "$@"
 else
     # if not run via terminal, log everything into a log file
      perform_update >> /var/log/pi-star/WPSD-update.log 2>&1
